name: KitPvPCore
version: 1.0-RELEASE
main: wtf.tekoh.KitPvPCore.Core
description: A KitPvP Core made by Tekoh
depend: [Vault]

commands:
  kitpvp:
    usage: /<command>
    description: Plugin info.
  freeze:
    usage: /<command>
    description: Freeze a player.
    aliases: [ss, f]
  staffchat:
    usage: /<command>
    description: Use staffchat.
    aliases: [c, sc]
  report:
    usage: /<command>
    description: Report a player.
  chat:
    usage: /<command>
    description: Chat options
  rename:
    usage: /<command>
    description: Rename
  discord:
    usage: /<command>
    description: Discord server
  website:
    usage: /<command>
    description: Website
  store:
    usage: /<command>
    description: Store
  support:
    usage: /<command>
    description: support