name: KitPvPCore
version: 0.1
main: me.tekoh.KitPvPCore.Core
description: A KitPvP Core made by Tekoh/MaxTheMango
depend: [Vault]

commands:
  kitpvp:
    usage: /<command>
    description: Plugin info.
  freeze:
    usage: /<command>
    description: Freeze a player.
    aliases: [ss, f]
  staffchat:
    usage: /<command>
    description: Use staffchat.
    aliases: [c, sc]
  report:
    usage: /<command>
    description: Report a player.
  chat:
    usage: /<command>
    description: Chat options
  rename:
    usage: /<command>
    description: Rename