name: KitPvPCore
version: 1.0-RELEASE
main: wtf.tekoh.KitPvPCore.Core
description: A KitPvP Core made by Tekoh
depend: [Vault]

commands:
  kitpvp:
    usage: /<command>
    description: Plugin info.
  freeze:
    usage: /<command> <player>
    description: Freeze a player.
    aliases: [ss]
  staffchat:
    usage: /<command> <message>
    description: Use staffchat.
    aliases: [sc]
  report:
    usage: /<command> <report> <reason>
    description: Report a player.
  chat:
    usage: /<command>
    description: Chat options
  rename:
    usage: /<command> <name>
    description: Rename an item
  discord:
    usage: /<command>
    description: Discord server
  website:
    usage: /<command>
    description: Website link
  store:
    usage: /<command>
    description: Store link
  support:
    usage: /<command> <request>
    description: Get support from staff
    aliases: [helpop]